// <auto-generated />
using Christofel.CtuAuth.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Christofel.Api.Migrations
{
    [DbContext(typeof(ApiCacheContext))]
    [Migration("20250608090056_AddAnnotations")]
    partial class AddAnnotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Api")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Christofel.CtuAuth.Database.AssignRole", b =>
                {
                    b.Property<long>("AssignRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AssignRoleId"));

                    b.Property<bool>("Add")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("GuildDiscordId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserDiscordId")
                        .HasColumnType("bigint");

                    b.HasKey("AssignRoleId");

                    b.ToTable("AssignRole", "Api");
                });
#pragma warning restore 612, 618
        }
    }
}
