schema {
  query: Query
  mutation: Mutation
}

"The node interface is implemented by entities that have a global unique identifier."
interface Node {
  id: ID!
}

type Mutation {
  registerDiscord(input: RegisterDiscordInput!): RegisterDiscordPayload!
  registerCtuFel(input: RegisterCtuInput!): RegisterCtuPayload!
  registerCtuToken(input: RegisterCtuTokenInput!): RegisterCtuPayload!
}

type Query {
  verifyRegistrationCode(input: VerifyRegistrationCodeInput!): VerifyRegistrationCodePayload!
}

type RegisterCtuPayload {
  user: User
  errors: [UserError!]!
}

type RegisterDiscordPayload {
  user: User
  registrationCode: String!
  errors: [UserError!]!
}

"Database table that holds authenticated users\nor users in auth process."
type User implements Node {
  "Gets or sets the primary key of DbUser."
  id: ID!
  "Gets Discord id of the user."
  discordId: UnsignedLong
  "Gets or sets last date of authentication."
  authenticatedAt: DateTime
  "Gets or sets CTU account username."
  ctuUsername: String
  "Gets or sets whether the duplicity was approved."
  duplicityApproved: Boolean!
  "Gets or sets code used for registration purposes."
  registrationCode: String
  "Gets the interaction id associated with the registration."
  interactionToken: String
  "Date and time of creation of the entity."
  createdAt: DateTime!
  "Date and time of update of the entity, set if the entity was updated."
  updatedAt: DateTime
}

type UserError {
  errorCode: UserErrorCode!
  message: String!
}

type VerifyRegistrationCodePayload {
  verificationStage: RegistrationCodeVerification!
  errors: [UserError!]!
}

input RegisterCtuInput {
  oauthCode: String!
  redirectUri: String!
  registrationCode: String!
}

input RegisterCtuTokenInput {
  accessToken: String!
  registrationCode: String!
}

input RegisterDiscordInput {
  oauthCode: String!
  redirectUri: String!
}

input VerifyRegistrationCodeInput {
  registrationCode: String!
}

enum RegistrationCodeVerification {
  NOT_VALID
  DISCORD_AUTHORIZED
  CTU_AUTHORIZED
  DONE
}

enum UserErrorCode {
  UNSPECIFIED
  OAUTH_TOKEN_REJECTED
  REJECTED_DUPLICATE_USER
  USER_NOT_IN_GUILD
  INVALID_REGISTRATION_CODE
  SOFT_AUTH_ERROR
}

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")

"Snowflake ulong type"
scalar UnsignedLong